name: CI/CD Pipeline

on:
  push:
    branches: [ "main", "feature/pipeline-fix", "trivy" ]

jobs:

  build:
    name: Build du projet
    runs-on: ubuntu-latest

    steps:
      - name: Récupération du code
        uses: actions/checkout@v3

      - name: Vérification des fichiers
        run: ls -la

      - name: Test simple
        run: echo "Build réussi"

  scan-trivy:
    name: Scan sécurité avec Trivy
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Récupération du code
        uses: actions/checkout@v3

      - name: Scan des vulnérabilités
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          scan-ref: .
          format: table
          exit-code: 0

  deploy:
    name: Déploiement
    runs-on: ubuntu-latest
    needs: scan-trivy

    steps:
      - name: Déploiement simulé
        run: echo "Déploiement effectué avec succès"
